---
title: "台北市竊盜地圖"
runtime: shiny
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggmap)
library(mapproj)
library(spdep)
library(maptools)
library(magrittr)
library(dplyr)
library(ggplot2)
library(readr)

shp_file_name="/Users/sary357/Downloads/R_Report/TOWN_MOI_1060831.shp"
data_file_name="/Users/sary357/Downloads/R_Report/stolen_in_taipei_10401_10608.csv"
people_distribution_file_name="/Users/sary357/Downloads/R_Report/opendata10608M030.csv"

plot_stolen_in_each_district_in_taipei=function(map_type, data_set, boarder_points, district_name){
 
  plotDf<-data_set %>% select(.,district, lat, lon) %>% filter(.,district==district_name) 
  plot_area<- boarder_points[boarder_points@data$TOWNNAME==district_name,]
  map<-get_googlemap(center = c(lon=median(plotDf$lon),lat=median(plotDf$lat)),
                 
                 zoom = 14,
                 language = "zh-TW", 
                 maptype = map_type,  force = FALSE, archiving = TRUE)  
  #map<-get_map(location = c(lon=median(plotDf$lon),lat=median(plotDf$lat)),
  #               source = "google", 
  #               zoom = 14,
  #               language = "zh-TW", 
  #               maptype = map_type,  force = FALSE)  
  map %>% ggmap() +geom_polygon(aes(x = long, y = lat), 
                           data = plot_area,size=0.001, color="black",alpha=0.2)+stat_density2d(data = plotDf, aes(x = lon, y=lat,fill = ..level.., alpha = ..level..),size = 0.01, bins = 16, geom = "polygon") +scale_fill_gradient(low = "green", high = "red",guide = FALSE)+scale_alpha(range = c(0, 0.5), guide = FALSE)
  
  
}

# load data
maptype<-"roadmap"
file_name=data_file_name
stolen_point <- read_csv(file_name)
tw.map <- maptools::readShapeSpatial(shp_file_name)
taipei<-tw.map[tw.map@data$COUNTYNAME=="臺北市",] 


addr<-stolen_point$定位地點
district_lat<-stolen_point$lat
district_lon<-stolen_point$lon
district<-substr(addr, 4, 6)
df<-data.frame("district"=district, "lat"=district_lat, "lon"=district_lon)
```

## Dataset - 竊盜地圖
```{r stolen_data , echo=F}
renderTable(
  {head(stolen_point %>% select(發生日期, 發生地點,lat,lon), 10)}
)
```

## Dataset- 實價登錄
```{r pricing_map, echo=F}
print("TBD")
```

## 全台北市的竊盜熱點地圖
```{r taipei_stolen_map, echo=FALSE, warning=FALSE, comment=FALSE, message=F}

map <- get_map(location = c(lon=median(stolen_point$lon),lat=median(stolen_point$lat)),
               source = "google", 
               zoom = 12,
               language = "zh-TW", 
               maptype = maptype)

ggmap(map) +geom_point(aes(x = long, y = lat), 
                         data = taipei,size=0.001, color="black",alpha=0.1)+stat_density2d(data = stolen_point, aes(x = lon, y=lat,fill = ..level.., alpha = ..level..),size = 0.01, bins = 16, geom = "polygon") +scale_fill_gradient(low = "green", high = "red",guide = FALSE)+scale_alpha(range = c(0, 0.5), guide = FALSE)

```

- 台北市全區中, 我們可以知道從 2015 年 1 月到 2017 年 8 月在中山區及萬華區是台北市 12 行政區中住宅竊盜高度相對集中的行政區

## 分區統計(1)
- 竊盜數量統計前 6 名行政區

```{r simple_statistics_in_each_district, echo=FALSE}
simpleDistrict<-df %>% group_by(district) %>% summarise(m=n()) %>% arrange(.,-m)
renderTable(
  {colnames(simpleDistrict) <- c("行政區", "住宅竊盜數量")
    simpleDistrict %>% top_n(6)
    }
)

```

## 分區統計(2)
- 每一個行政區每一千戶的平均竊盜案數目

```{r simple_graph_show_percentage, echo=FALSE, warning=FALSE, comment=FALSE, message=F}

df_people <-  read_csv(people_distribution_file_name)
df_1<-df_people %>% filter(.,grepl('臺北市', site_id)) %>% filter(household_no >0)%>%select(site_id,household_no) %>% group_by(household_no) 
#df_1 %>% View
df_1$site_id<-as.factor(df_1$site_id)
df_1$household_no<-as.numeric(df_1$household_no)
df_1<-aggregate(df_1$household_no, by=list(site_id=df_1$site_id), FUN=sum)
df_1$site_id<-substr(df_1$site_id, 4, 6)
colnames(df_1) <- c("district", "household_no")
df_3<-merge(simpleDistrict, df_1, by=c("district"))

df_3.percentage <- df_3$m/df_3$household_no*1000 # 得到每一區竊盜數目/千戶數
df_4<-mutate(df_3,df_3.percentage)
df_4 %>% ggplot( mapping=aes(x=district,y=df_3.percentage,fill=-df_3.percentage)) + geom_bar(stat="identity") +xlab("台北市行政區")+ylab("每一千戶發生竊盜案的數目")+theme(text = element_text(family = 'SimSun')) +guides(fill=FALSE)



```

## 分區統計(小結)
- 從上方圖表中, 可以看出中山區的 2015 年 1 月到 2017 年 8 月住宅竊盜案件數較其他行政區高出許多
- 萬華區的件數並不是特別高, 但集中於萬華區的某特定區域 (萬華龍山寺附近)
- 中正區每一千戶的竊盜數量和萬華區相當
- 文山區相對來說其他行政區中竊盜案數量是最低的

## 分區熱點分析
- 請選擇不同行政區查看個行政區的熱點分析

```{r eruptions}
inputPanel(
  selectInput("districtChosen", label = "District of Taipei:",
              choices = c('中山區', '萬華區','中正區','大同區','松山區',                          '大安區','信義區','文山區','南港區','內湖區','士林區','北投區'), selected = '中山區')
  )
renderPlot({
  if(input$districtChosen=='')
    plot_stolen_in_each_district_in_taipei(maptype,df,taipei,'中山區')
  else
    plot_stolen_in_each_district_in_taipei(maptype,df,taipei,input$districtChosen)
})

```


